
[tool.uv]
package = false

[tool.ruff]
line-length   = 120
output-format = "concise"

[tool.ruff.lint] # Ruff linting rules found at https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "COM812",  # Missing trailing comma (conflicts with ruff's formatter)
    "D203",    # Missing blank line after class docstring (alternative to D211)
    "D213",    # Docstring summary should start on the second line (alternative to D212)
    "EM",      # Assign exception strings to variables before raising them
    "ERA",     # Avoid commented-out code; check during CI/CD instead
    "F401",    # Avoid unused imports (check during pre-commit instead and CI/CD instead)
    "FBT001",  # Avoid positional boolean arguments, checked via type hints
    "FBT002",  # Avoid positional boolean arguments, checked via default values
    "FIX002",  # Avoid TODO comments
    "G004",    # Avoid f-strings in logging statements
    "PLR2004", # Avoid magic values in comparisons
    "S101",    # Avoid assert statements
    "S603",    # Avoid subprocess calls without validated input (prone to false positives)
    "S607",    # Avoid starting a process with a partial executable path
    "T201",    # Avoid using print()
    "TD002",   # Missing author in TODO comment
    "TD003",   # Missing issue link in TODO comment
    "TRY003",  # Avoid long exception messages outside the exception class
]
unfixable = []

[tool.ruff.lint.per-file-ignores]

[tool.ruff.lint.pylint]
max-args = 8

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.ty.terminal]
output-format = "concise"
